services:
  scrappy:
    image: ghcr.io/ginkodan/scrappy:latest
    ports:
      - "3000:3000"
    volumes:
      - scrappy-data:/app/data
    env_file:
      - .env
    restart: unless-stopped

  docs:
    image: ghcr.io/ginkodan/scrappy-docs:latest
    ports:
      - "3001:80"
    restart: unless-stopped

volumes:
  scrappy-data:
