[build]
builder = "nixpacks"
buildCommand = "npm install && cd ui && npm install && npm run build && cd .."

[deploy]
startCommand = "npm run server"
healthcheckPath = "/jobs"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
